[component]
array_structures = ["content_blocks"]
label = "Calculator"
description="Section for calculator inputs"
icon = "info_outline"
tags=["content"]

[props]
theme.select = ["Purple", "White", "Pink"]

[props.main-img]
image = "/assets/pizza_bottom.svg"
alt = "Pizza on a board"

[props.heading] 
text= "Pizza Calculator"

[props.calc-var]
heading = "Pizza Calculator"
inputbox = "3"
class = "num-pizza"
type = "number"
min = "0"
max = "10"
value = "1"

[props.calc-h2o]
heading = "Water %"
inputbox = "3"
class = "num-pizza"
type = "number"
min = 50
max = 70
value = 57


