title: Make your own Pizza
email: jan@cloudcannon.com
description: >- # this means to ignore newlines until "baseurl:"
  Pizza recipe and calculator site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: janclaasen
github_username:  YodaSoda

bookshop_locations:
  - ../components

plugins:
  - jekyll-bookshop
  - bookshop-array-structures
  - jekyll-postcss

_array_structures:
  content_blocks:
    style: modal
  page_sections:
    values:
      - label: Page Section
        icon: crop_7_5
        value:
          slug:
          bg_color: white
          alignment: center
          content_blocks: