[component]
array_structures = ["content_blocks"]
label = "Header"
description="Generic info section"
icon = "psychology"
tags=["content"]

[props]

[props.logo]
image = "/assets/logo.svg"
alt = "Pizza Logo"